/*
 * Translator Knowledge Beacon API
 * This is the nDexBio (www.ndexbio.org) biomedical graph archive wrapped with the  Translator Knowledge Beacon web service application programming interface (API). 
 *
 * OpenAPI spec version: 1.0.17
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BeaconConceptType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T13:58:42.219-07:00")
public class BeaconConceptType {
  @SerializedName("id")
  private String id = null;

  @SerializedName("iri")
  private String iri = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("frequency")
  private Integer frequency = null;

  public BeaconConceptType id(String id) {
    this.id = id;
    return this;
  }

   /**
   * the CURIE of the type
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "the CURIE of the type")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BeaconConceptType iri(String iri) {
    this.iri = iri;
    return this;
  }

   /**
   * The full IRI, generally resolve the full semantic description of the type
   * @return iri
  **/
  @ApiModelProperty(example = "null", value = "The full IRI, generally resolve the full semantic description of the type")
  public String getIri() {
    return iri;
  }

  public void setIri(String iri) {
    this.iri = iri;
  }

  public BeaconConceptType label(String label) {
    this.label = label;
    return this;
  }

   /**
   * human readable name (\"rdfs:label\")
   * @return label
  **/
  @ApiModelProperty(example = "null", value = "human readable name (\"rdfs:label\")")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public BeaconConceptType frequency(Integer frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * the number of concept entries of the specified type in the beacon knowledge base
   * @return frequency
  **/
  @ApiModelProperty(example = "null", value = "the number of concept entries of the specified type in the beacon knowledge base")
  public Integer getFrequency() {
    return frequency;
  }

  public void setFrequency(Integer frequency) {
    this.frequency = frequency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeaconConceptType beaconConceptType = (BeaconConceptType) o;
    return Objects.equals(this.id, beaconConceptType.id) &&
        Objects.equals(this.iri, beaconConceptType.iri) &&
        Objects.equals(this.label, beaconConceptType.label) &&
        Objects.equals(this.frequency, beaconConceptType.frequency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, iri, label, frequency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeaconConceptType {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    iri: ").append(toIndentedString(iri)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

