/*
 * Translator Knowledge Beacon API
 * This is the nDexBio (www.ndexbio.org) biomedical graph archive wrapped with the  Translator Knowledge Beacon web service application programming interface (API). 
 *
 * OpenAPI spec version: 1.0.17
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.api;

import bio.knowledge.client.ApiException;
import bio.knowledge.client.model.BeaconConceptType;
import bio.knowledge.client.model.BeaconKnowledgeMapStatement;
import bio.knowledge.client.model.BeaconPredicate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MetadataApi
 */
@Ignore
public class MetadataApiTest {

    private final MetadataApi api = new MetadataApi();

    
    /**
     * 
     *
     * Get a list of types and # of instances in the knowledge source, and a link to the API call for the list of equivalent terminology 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConceptTypesTest() throws ApiException {
        List<BeaconConceptType> response = api.getConceptTypes();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get a high level knowledge map of the all the beacons by subject semantic type, predicate and semantic object type 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKnowledgeMapTest() throws ApiException {
        List<BeaconKnowledgeMapStatement> response = api.getKnowledgeMap();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get a list of predicates used in statements issued by the knowledge source 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPredicatesTest() throws ApiException {
        List<BeaconPredicate> response = api.getPredicates();

        // TODO: test validations
    }
    
}
